# Generated by Django 2.2 on 2020-06-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(max_length=20)),
                ('customer_number', models.CharField(max_length=20)),
                ('feedback_on', models.BooleanField()),
                ('message_category', models.CharField(choices=[('REQU', 'Request Sent'), ('REPL', 'Customer Reply'), ('RATE', 'Customer Reply with Rating')], max_length=30)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=160)),
                ('created_at', models.DateTimeField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.Place')),
            ],
        ),
    ]
