# Generated by Django 2.2 on 2020-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200604_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, choices=[('SENDING', 'Sending'), ('SENT', 'Sent'), ('CANCELED', 'Canceled'), ('INCOMPLETED', 'Incompleted')], max_length=11, null=True),
        ),
    ]
