# Generated by Django 2.2 on 2020-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200604_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, choices=[('SENDING', 'Sending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('CANCELED', 'Canceled'), ('INCOMPLETED', 'Incompleted')], max_length=11, null=True),
        ),
    ]
