# Generated by Django 2.2 on 2020-07-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20200730_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryModel',
        ),
    ]
