# Generated by Django 2.2 on 2020-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_delete_celerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_campaign_sent',
            field=models.BooleanField(default=False),
        ),
    ]
