# Generated by Django 2.2 on 2020-08-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_scheduled_campaign_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduled_campaign_sent',
            new_name='scheduled_sent_to_celery',
        ),
    ]
