# Generated by Django 2.2 on 2020-07-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='businessperson',
        ),
    ]
