# Generated by Django 2.2 on 2020-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_remove_link_businessperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_link_type', models.CharField(choices=[('FEED', 'Feeback'), ('GOOG', 'Google'), ('FB', 'Facebook'), ('YELP', 'Yelp')], max_length=30, unique=True)),
            ],
        ),
    ]
