# Generated by Django 2.2 on 2020-07-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20200717_0130'),
        ('links', '0003_reviewlinktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.TextField()),
                ('long_url', models.TextField()),
                ('short_url', models.CharField(max_length=60)),
                ('review_link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.ReviewLinkType')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Place')),
            ],
            options={
                'unique_together': {('store', 'review_link_type')},
            },
        ),
    ]
