# Generated by Django 2.2 on 2020-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'processing'), ('UPTODATE', 'up to date'), ('PROBLEM', 'error processing')], max_length=16, null=True),
        ),
    ]
