# Generated by Django 2.2 on 2020-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0002_audience_audience_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
