# Generated by Django 2.2 on 2020-07-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0003_auto_20200611_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='businessperson',
        ),
    ]
