# Generated by Django 2.2 on 2020-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0004_remove_audience_businessperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
