# Generated by Django 2.2 on 2020-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0007_globalunsubscriber_unsubscribed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalunsubscriber',
            name='staff_unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
