# Generated by Django 2.2 on 2020-11-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_auto_20201104_0706'),
        ('audiences', '0008_globalunsubscriber_staff_unsubscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDefaultAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Place', unique=True)),
            ],
        ),
    ]
