# Generated by Django 2.2 on 2020-11-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0009_storedefaultaudience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedefaultaudience',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.Place'),
        ),
    ]
