# Generated by Django 2.2 on 2020-06-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='monthly_sms_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
