# Generated by Django 2.2 on 2020-06-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_place_monthly_sms_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='monthly_sub_uploads_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
