# Generated by Django 2.2 on 2020-07-11 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0005_auto_20200615_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='businessperson',
        ),
        migrations.AddField(
            model_name='place',
            name='businessperson',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
