# Generated by Django 2.2 on 2020-07-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20200717_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feedback_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='feedback_link_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
