# Generated by Django 2.2 on 2020-07-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20200717_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
