# Generated by Django 2.2 on 2020-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20200717_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='monthly_sms',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='place',
            name='monthly_sms_limit',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='place',
            name='monthly_sub_uploads',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='place',
            name='monthly_sub_uploads_limit',
            field=models.IntegerField(default=2000),
        ),
    ]
