# Generated by Django 2.2 on 2020-07-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_place_main_review_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='feedback_link',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feedback_link_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_link',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_link_id',
        ),
    ]
