# Generated by Django 2.2 on 2020-08-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_auto_20200727_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_store_number', models.CharField(max_length=20)),
                ('unformatted_store_number', models.IntegerField()),
                ('google_rating', models.FloatField()),
                ('google_reviews_total', models.IntegerField()),
                ('store_category', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(max_length=250)),
                ('hours_mon', models.CharField(max_length=250)),
                ('hours_tue', models.CharField(max_length=250)),
                ('hours_wed', models.CharField(max_length=250)),
                ('hours_thu', models.CharField(max_length=250)),
                ('hours_fri', models.CharField(max_length=250)),
                ('hours_sat', models.CharField(max_length=250)),
                ('hours_sun', models.CharField(max_length=250)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.Place')),
            ],
        ),
    ]
