# Generated by Django 2.2 on 2020-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_placedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedetail',
            name='place_map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
