# Generated by Django 2.2 on 2020-08-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_placedetail_place_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetail',
            name='formatted_store_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='placedetail',
            name='unformatted_store_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
