# Generated by Django 2.2 on 2020-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_remove_placedetail_unformatted_store_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedetail',
            name='unformatted_store_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
