# Generated by Django 2.2 on 2020-10-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_auto_20200817_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='store_number',
            field=models.CharField(default='no number listed', max_length=30),
        ),
    ]
