# Generated by Django 3.1.13 on 2021-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_auto_20201104_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='basic_advup',
            field=models.BooleanField(default=False),
        ),
    ]
